# Generated by Django 3.1.2 on 2020-11-01 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abc_app', '0003_case_caselink'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='accounts',
            field=models.ManyToManyField(through='abc_app.CaseLink', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caselink',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caselink', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caselink',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caselink', to='abc_app.case'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedent', models.CharField(max_length=60)),
                ('behavior', models.CharField(max_length=60)),
                ('consequence', models.CharField(max_length=60)),
                ('time', models.DateTimeField(verbose_name='Time of Incident')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='abc_app.case')),
            ],
        ),
    ]
