# Generated by Django 3.1.2 on 2020-11-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abc_app', '0004_auto_20201101_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date of Incident'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='Time of Incident'),
        ),
    ]
