# Generated by Django 3.1.2 on 2020-11-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abc_app', '0005_auto_20201101_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='dob',
            field=models.DateField(auto_now=True, verbose_name='Date of Birth'),
        ),
    ]
