# Generated by Django 3.1.2 on 2020-11-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abc_app', '0006_auto_20201101_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
