# Generated by Django 3.1.2 on 2020-11-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abc_app', '0008_auto_20201101_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='time',
            field=models.TimeField(verbose_name='Time of Incident'),
        ),
    ]
